### ISSUE TITLE
Minimal example

### ISSUE THREAD

**Issue by guaraqe** [liamoc/latex-formulae#1]
Hello! Thanks for the nice library! I just wanted to say that your example of minimal setup for Hakyll does not really work. After some playing, the simplest I got was:

    customCompiler :: ReaderOptions -> WriterOptions
            -> (Item Pandoc -> Compiler (Item Pandoc))
            -> Compiler (Item String)
    customCompiler ropt wopt f = 
        writePandocWith wopt <$> (f =<< readPandocWith ropt =<< getResourceBody)

    main = do
           renderFormulae <- initFormulaCompilerDataURI 1000 defaultEnv
           hakyll $
             match "posts/*" $ do
               route $ setExtension "html"
               compile $ customCompiler defaultHakyllReaderOptions defaultHakyllWriterOptions
                         (renderFormulae defaultPandocFormulaOptions)

The default compiler from Hakyll does not work because it applies traverse to `f` in the first function. Adding this example to the docs would probably help new users. Adding the custom compiler would make things even easier.

**Comment by liamoc** [comment]
The customCompiler you wrote looks a lot like the built-in withTransformM compiler in Hakyll? What about it doesn't work?

**Comment by liamoc** [comment]
Fixed in 005acc7fee964be245e9de3fba6178b268e05592
