### ISSUE TITLE
Support newer versions of GHC

### ISSUE THREAD

**Issue by aligusnet** [liamoc/latex-formulae#8]
Hello,

do you mind to support newer versions of GHC and latest Haskell LTS?

Right now upper bound of base does not allow it. I would recommend changing the bound for base to base < 5.0. And remove version constraints for other packages. Like I have done here: https://github.com/aligusnet/latex-formulae/commit/55026b36e74bc65211a27a0a307740973d8199e8

In most cases, it works just fine and allows using the package with newer compiler's versions without pain and hassle :)

**Comment by liamoc** [comment]
I'd rather leave version bounds in for cabal users.
